spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/armyfr
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ghdwnsrl7777@gmail.com
    password: 0219jk0114wk!@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  mvc:
    hiddenmethod:
      filter:
        enabled:  true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

info:
  build:
    firebase-configuration-file: "armyfr-50941-firebase-adminsdk-3ymiy-18e427a7b5.json"
